package com.game.shared.protocol.core;

/**
 * Enumerates the message types currently planned for the shared protocol.
 * @since 0.1.0
 */
public enum Opcode {
    LOGIN_REQUEST,LOGIN_RESPONSE,
    REGISTER_REQUEST,REGISTER_RESPONSE,
    CHARACTER_CREATE_REQUEST, CHARACTER_CREATE_RESPONSE,
    CHARACTER_LIST,
    ENTER_WORLD, ENTER_WORLD_ACK,
    WORLD_SNAPSHOT,
    ENTITY_SPAWN,ENTITY_DESPAWN,ENTITY_MOVE,
    CHAT_MESSAGE,
    ATTACK,DAMAGE,
    INTERACT, INTERACTION_MESSAGE,
    PICKUP_LOOT,
    EQUIP_ITEM,
    INVENTORY_UPDATE,
    WORLD_PING,
    ERROR
}
